CREATE TABLE data_buffer (
    data_buffer_id          bigserial PRIMARY KEY,

    current_weather_id      bigint NOT NULL,
    observed_at             timestamptz NOT NULL,
    sunrise_at              timestamptz,
    sunset_at               timestamptz,
    temp                    numeric(5, 2) NOT NULL,
    feels_like              numeric(5, 2),
    pressure                integer,
    humidity                smallint,
    dew_point               numeric(5, 2),
    uvi                     numeric(4, 2),
    clouds                  smallint,
    visibility              integer,
    wind_speed              numeric(5, 2),
    wind_deg                smallint,
    wind_gust               numeric(5, 2),
    rain_1h                 numeric(5, 2),
    snow_1h                 numeric(5, 2),
    location_id1            bigint NOT NULL,
    condition_id            bigint NOT NULL,

    condition_id_1          bigint NOT NULL,
    openweather_weather_id  integer NOT NULL,
    main                    varchar(50) NOT NULL,
    description             varchar(100) NOT NULL,
    icon                    varchar(4),

    daily_forecast_id       bigint NOT NULL,
    forecast_date           date NOT NULL,
    retrieved_at            timestamptz NOT NULL,
    sunrise_at_1            timestamptz,
    sunset_at_1             timestamptz,
    moonrise_at             timestamptz,
    moonset_at              timestamptz,
    moonphase               numeric(3, 2),
    temp_day                numeric(5, 2),
    temp_min                numeric(5, 2),
    temp_max                numeric(5, 2),
    temp_night              numeric(5, 2),
    temp_evening            numeric(5, 2),
    temp_morning            numeric(5, 2),
    feels_like_day          numeric(5, 2),
    feels_like_night        numeric(5, 2),
    pressure_1              integer,
    humidity_1              smallint,
    dew_point_1             numeric(5, 2),
    wind_speed_1            numeric(5, 2),
    wind_deg_1              smallint,
    wind_gust_1             numeric(5, 2),
    clouds_1                smallint,
    pop                     numeric(4, 3),
    rain                    numeric(6, 2),
    snow                    numeric(6, 2),
    uvi_1                   numeric(4, 2),
    location_id             bigint NOT NULL,
    condition_id_2          bigint NOT NULL,

    air_pollution_id        bigint NOT NULL,
    observed_at_1           timestamptz NOT NULL,
    aqi                     smallint NOT NULL,
    co                      numeric(8, 2),
    no                      numeric(8, 2),
    no2                     numeric(8, 2),
    o3                      numeric(8, 2),
    so2                     numeric(8, 2),
    pm2_5                   numeric(8, 2),
    pm10                    numeric(8, 2),
    location_id_2           bigint NOT NULL,

    minutely_forecast_id    bigint NOT NULL,
    forecast_for            timestamptz,
    retrieved_at_1          timestamptz,
    precipitation           numeric(5, 2),
    location_id_3           bigint NOT NULL,

    hourly_forecast_id      bigint NOT NULL,
    forecast_for_1          timestamptz,
    retrieved_at_2          timestamptz NOT NULL,
    temp_7                  numeric(5, 2) NOT NULL,
    feels_like_3            numeric(5, 2),
    pressure_2              integer,
    humidity_2              smallint,
    dew_point_2             numeric(5, 2),
    uvi_2                   numeric(4, 2),
    clouds_2                smallint,
    visibility_1            integer,
    pop_1                   numeric(4, 3),
    wind_speed_2            numeric(5, 2),
    wind_deg_2              smallint,
    wind_gust_2             numeric(5, 2),
    rain_1h_1               numeric(5, 2),
    snow_1h_1               numeric(5, 2),
    location_id_4           bigint NOT NULL,
    condition_id_3          bigint NOT NULL,

    location_id_5           bigint NOT NULL,
    city_name               varchar(100),
    country_code            char(2),
    lat                     numeric(8, 5) NOT NULL,
    lon                     numeric(8, 5) NOT NULL,
    timezone                varchar(64),
    timezone_offset         integer,

    weather_alert_id        bigint NOT NULL,
    sender_name             varchar(150),
    event                   varchar(150) NOT NULL,
    start_at                timestamptz NOT NULL,
    end_at                  timestamptz NOT NULL,
    description_1           text,
    tags                    text,
    location_id_6           bigint NOT NULL,


    CONSTRAINT chk_data_buffer_humidity CHECK (humidity IS NULL OR humidity BETWEEN 0 AND 100),
    CONSTRAINT chk_data_buffer_humidity_1 CHECK (humidity_1 IS NULL OR humidity_1 BETWEEN 0 AND 100),
    CONSTRAINT chk_data_buffer_humidity_2 CHECK (humidity_2 IS NULL OR humidity_2 BETWEEN 0 AND 100),
    CONSTRAINT chk_data_buffer_clouds CHECK (clouds IS NULL OR clouds BETWEEN 0 AND 100),
    CONSTRAINT chk_data_buffer_clouds_1 CHECK (clouds_1 IS NULL OR clouds_1 BETWEEN 0 AND 100),
    CONSTRAINT chk_data_buffer_clouds_2 CHECK (clouds_2 IS NULL OR clouds_2 BETWEEN 0 AND 100),
    CONSTRAINT chk_data_buffer_wind_deg CHECK (wind_deg IS NULL OR wind_deg BETWEEN 0 AND 360),
    CONSTRAINT chk_data_buffer_wind_deg_1 CHECK (wind_deg_1 IS NULL OR wind_deg_1 BETWEEN 0 AND 360),
    CONSTRAINT chk_data_buffer_wind_deg_2 CHECK (wind_deg_2 IS NULL OR wind_deg_2 BETWEEN 0 AND 360),
    CONSTRAINT chk_data_buffer_pop CHECK (pop IS NULL OR pop BETWEEN 0 AND 1),
    CONSTRAINT chk_data_buffer_pop_1 CHECK (pop_1 IS NULL OR pop_1 BETWEEN 0 AND 1),
    CONSTRAINT chk_data_buffer_aqi CHECK (aqi BETWEEN 1 AND 5),
    CONSTRAINT chk_data_buffer_lat CHECK (lat BETWEEN -90 AND 90),
    CONSTRAINT chk_data_buffer_lon CHECK (lon BETWEEN -180 AND 180),
    CONSTRAINT chk_data_buffer_country_code CHECK (country_code IS NULL OR length(country_code) = 2),
    CONSTRAINT chk_data_buffer_alert_time_order CHECK (end_at >= start_at)
);
