CREATE SCHEMA IF NOT EXISTS stg;

CREATE TABLE IF NOT EXISTS stg.mapped_data_buffer (
    mapped_data_buffer_id bigint,
    fetched_at timestamptz,

    location_city_name varchar(100),
    location_country_code char(2),
    location_lat numeric(8, 5),
    location_lon numeric(8, 5),
    location_timezone varchar(64),
    location_timezone_offset integer,

    current_observed_at timestamptz,
    current_sunrise_at timestamptz,
    current_sunset_at timestamptz,
    current_temp numeric(5, 2),
    current_feels_like numeric(5, 2),
    current_pressure integer,
    current_humidity smallint,
    current_dew_point numeric(5, 2),
    current_uvi numeric(4, 2),
    current_clouds smallint,
    current_visibility integer,
    current_wind_speed numeric(5, 2),
    current_wind_deg smallint,
    current_wind_gust numeric(5, 2),
    current_rain_1h numeric(5, 2),
    current_snow_1h numeric(5, 2),
    current_openweather_weather_id bigint,
    current_condition_main varchar(50),
    current_condition_description varchar(100),
    current_condition_icon varchar(4),

    daily_forecast_date date,
    daily_retrieved_at timestamptz,
    daily_sunrise_at timestamptz,
    daily_sunset_at timestamptz,
    daily_moonrise_at timestamptz,
    daily_moonset_at timestamptz,
    daily_moonphase numeric(3, 2),
    daily_temp_day numeric(5, 2),
    daily_temp_min numeric(5, 2),
    daily_temp_max numeric(5, 2),
    daily_temp_night numeric(5, 2),
    daily_temp_evening numeric(5, 2),
    daily_temp_morning numeric(5, 2),
    daily_feels_like_day numeric(5, 2),
    daily_feels_like_night numeric(5, 2),
    daily_pressure integer,
    daily_humidity smallint,
    daily_dew_point numeric(5, 2),
    daily_wind_speed numeric(5, 2),
    daily_wind_deg smallint,
    daily_wind_gust numeric(5, 2),
    daily_clouds smallint,
    daily_pop numeric(4, 3),
    daily_rain numeric(6, 2),
    daily_snow numeric(6, 2),
    daily_uvi numeric(4, 2),
    daily_openweather_weather_id bigint,
    daily_condition_main varchar(50),
    daily_condition_description varchar(100),
    daily_condition_icon varchar(4),

    hourly_forecast_for timestamptz,
    hourly_retrieved_at timestamptz,
    hourly_temp numeric(5, 2),
    hourly_feels_like numeric(5, 2),
    hourly_pressure integer,
    hourly_humidity smallint,
    hourly_dew_point numeric(5, 2),
    hourly_uvi numeric(4, 2),
    hourly_clouds smallint,
    hourly_visibility integer,
    hourly_pop numeric(4, 3),
    hourly_wind_speed numeric(5, 2),
    hourly_wind_deg smallint,
    hourly_wind_gust numeric(5, 2),
    hourly_rain_1h numeric(5, 2),
    hourly_snow_1h numeric(5, 2),
    hourly_openweather_weather_id bigint,
    hourly_condition_main varchar(50),
    hourly_condition_description varchar(100),
    hourly_condition_icon varchar(4),

    minutely_forecast_for timestamptz,
    minutely_retrieved_at timestamptz,
    minutely_precipitation numeric(5, 2),

    air_observed_at timestamptz,
    air_aqi smallint,
    air_co numeric(8, 2),
    air_no numeric(8, 2),
    air_no2 numeric(8, 2),
    air_o3 numeric(8, 2),
    air_so2 numeric(8, 2),
    air_pm2_5 numeric(8, 2),
    air_pm10 numeric(8, 2),
    air_nh3 numeric(8, 2),

    alert_sender_name varchar(150),
    alert_event varchar(150),
    alert_start_at timestamptz,
    alert_end_at timestamptz,
    alert_description text,
    alert_tags text
);
