[openweather]

OPENWEATHER_API_KEY=

BASE_CURRENT_WEATHER=https://api.openweathermap.org/data/3.0/onecall?lat={LAT}&lon={LON}&exclude=minutely,hourly,daily,alerts&units=metric&appid={OPENWEATHER_API_KEY}

BASE_DAILY_FORECAST=https://api.openweathermap.org/data/3.0/onecall?lat={LAT}&lon={LON}&exclude=current,minutely,hourly,alerts&units=metric&appid={OPENWEATHER_API_KEY}

BASE_HOURLY_FORECAST=https://api.openweathermap.org/data/3.0/onecall?lat={LAT}&lon={LON}&exclude=current,minutely,daily,alerts&units=metric&appid={OPENWEATHER_API_KEY}

BASE_MINUTELY_FORECAST=https://api.openweathermap.org/data/3.0/onecall?lat={LAT}&lon={LON}&exclude=current,hourly,daily,alerts&units=metric&appid={OPENWEATHER_API_KEY}

BASE_WEATHER_ALERTS=https://api.openweathermap.org/data/3.0/onecall?lat={LAT}&lon={LON}&exclude=current,minutely,hourly,daily&units=metric&appid={OPENWEATHER_API_KEY}

BASE_AIR_POLLUTION=https://api.openweathermap.org/data/2.5/air_pollution?lat={LAT}&lon={LON}&appid={OPENWEATHER_API_KEY}
